#!/usr/bin/env php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 'on');
ini_set('limit_memory','512M');
date_default_timezone_set('Asia/Shanghai');

define("__MODE__", "swoole");
define("__APP__",__DIR__);

define("__ROOT__",dirname(__DIR__));

define("__CONF__",__DIR__. '/conf.d');

/*
require (__DIR__ .'/vendor/autoload.php');

*/require (__ROOT__ . '/src/Ypf/Ypf.php');

spl_autoload_register("\\Ypf\\Ypf::autoload");

$setting = array(
	'root' => __DIR__,
	);
$app = new \Ypf\Swoole($setting);

//config
$config = new \Ypf\Lib\Config();
$config->load(__CONF__);

$app->setServerConfigIni(__CONF__ . '/server.conf');

$app->setWorkerConfigPath(__CONF__ . '/worker/');

$load = new \Ypf\Lib\Load(__ROOT__);
$app->set('load', $load);

//cache 
$cache = new \Ypf\Swoole\Cache(1024);
$app->set('cache', $cache);
$app->setCache($cache);

//memcache
$memcache = new \Ypf\Cache\Memcache($config->get("memcache.test"));
$app->set('memcache', $memcache);

//thread
$thread = new \Ypf\Swoole\Thread($cache);
$app->set('thread', $thread);

//request
$app->set('request', new \Ypf\Swoole\Request());

//response
$app->set('response', new \Ypf\Swoole\Response());

//view
$view = new \Cat\View(); 
$view->setTemplateDir(__APP__ . '/CatView/');
$app->set('view', $view);

$app->set('config', $config);

//$app->addPreAction("Cat\Common\Init\config");
$app->addPreAction("Cat\Common\Router\index");

$app->start();


